import type { Metadata } from "next";
import { Figtree } from "next/font/google";
import "./globals.css";
import { AOSInit } from "@/components/Layouts";

const figtree = Figtree({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Walikota.AI",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<AOSInit />
			<body className={figtree.className}>{children}</body>
		</html>
	);
}
